version: '3.8'
services:
  admin:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - admin_db

  admin_db:
    image: mysql:8.0.29
    environment:
      MYSQL_DATABASE: admin_microservices
      MYSQL_USER: root
      MYSQL_PASSWORD: admindb10
      MYSQL_ROOT_PASSWORD: admindb10
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
    - 33060:3306